# Generated by Django 3.2 on 2022-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lol',
            field=models.CharField(default='wew', max_length=255),
            preserve_default=False,
        ),
    ]
