# Generated by Django 3.2 on 2022-06-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_lol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lol',
        ),
    ]
